---

services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - type: bind
        source: ${PWD}/
        target: /rails-app/
      - type: volume
        source: bundle
        target: /usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      BINDING: 0.0.0.0

volumes:
  bundle:
