---

services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - type: bind
        source: ${PWD}/
        target: /rails-app/
      - type: volume
        source: bundle
        target: /usr/local/bundle
    ports:
      - '3000:3000'
    environment:
      BINDING: 0.0.0.0
      DB_HOST: db
    depends_on: ['db', 'db2']
  db:
    build:
      context: .
      dockerfile: ./dockerfiles/mysql/Dockerfile.debug
    command: ['./bin/mysqld', '--defaults-file=./my.cnf', '--user=root']
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      TZ: 'Asia/Tokyo'
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
      - type: bind
        source: ./dockerfiles/mysql/my.cnf
        target: /mysql-debug/mysql-server/build/my.cnf

    ports:
      - '3306:3306'
  # 2025年3月15日時点では、OSはoraclelinuxのみ
  db2:
    image: mysql:8.4-oracle
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      TZ: 'Asia/Tokyo'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '13306:3306'

volumes:
  bundle:
  db-data:
