# syntax=docker/dockerfile:1
# check=error=true

# このDockrfileは開発環境用です、本番環境では使用しないでください

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.2
FROM docker.io/library/ruby:$RUBY_VERSION

WORKDIR /rails-app

# ベースとなるパッケージをインストール
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y default-mysql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

#
# Note
#
# syntax=docker/dockerfile:1
# - Dockerfileの構文バージョンを指定
# - `docker/dockerfile:N`は、Dockerfile構文のバージョンNの最新リリースを使用を意味する
#
# check=error=true
# - ビルド時のチェックが警告ではなく、エラーになる
# - ビルド中に警告が発生するとビルドが失敗する
#
# BUNDLE_DEPLOYMENT
# Bundlerのデプロイモードの有効化・無効化
# - 1: 有効化
#   - Gemfile.lockとGemfileの不一致をチェック。これにより、依存関係の整合性を保つ
# - 0: 無効化(デフォルト: false)
#   - Gemfile.lockが更新されていない場合でも、Bundlerは警告やエラーを出さずにGemをインストール可能
#
# BUNDLE_PATH="/usr/local/bundle"
# - BundlerがGemをインストールするディレクトリを指定
#
# BUNDLE_WITHOUT="development"
# - Bundlerが特定のグループのGemをインストールしないように指定
# - ここでは「development」グループを指定
#
