#
# CI
#
jobs:
  - start-branch-filter:
      filters:
        branches:
          ignore:
            - /deploy.*/
  - hello:
      requires:
        - start-branch-filter
  - bundle-install:
      requires:
        - start-branch-filter
