# スケジュール実行(Trigger)の時は走らないようにする
# https://circleci.com/docs/ja/pipeline-variables/#pipeline-values
when:
  not:
    equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]

jobs:
  - start-branch-filter:
      filters:
        branches:
          ignore:
            - /deploy.*/
  - hello:
      requires:
        - start-branch-filter
