#
# Executor
#
references:
  ghcr_auth: &ghcr_auth
    username: $GHCR_PULL_USER
    password: $GHCR_PULL_TOKEN

executors:
  ruby:
    docker:
      - image: cimg/ruby:3.4.2
  my-ruby:
    resource_class: arm.medium
    docker:
      - &my_ruby
        image: ghcr.io/sunakan/circleci-rails-dev:latest
        auth:
          <<: *ghcr_auth
  my-ruby-with-mysql:
    resource_class: arm.medium
    docker:
      - <<: *my_ruby
      - image: ghcr.io/sunakan/circleci-rails-mysql:latest
        auth:
          <<: *ghcr_auth
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          TZ: 'Asia/Tokyo'
